var p = [
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 12:27:06",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 12:27:03",
        "descritpion": "首页管理",
        "permissionId": 1,
        "perName": "首页管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-tickets",
        "index": "1",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 14:12:36",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 14:12:34",
                "descritpion": "轮播图管理",
                "permissionId": 2,
                "perName": "轮播图管理",
                "url": "",
                "type": "2",
                "pid": 1,
                "icon": "",
                "index": "/bannerMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:22:34",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:22:36",
                        "descritpion": "新增",
                        "permissionId": 3,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 2,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:23:15",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:23:13",
                        "descritpion": "编辑",
                        "permissionId": 4,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 2,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:23:46",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:23:44",
                        "descritpion": "删除",
                        "permissionId": 5,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 2,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:03:01",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:02:59",
                        "descritpion": "禁用",
                        "permissionId": 13,
                        "perName": "禁用",
                        "url": "",
                        "type": "3",
                        "pid": 2,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:03:30",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:03:27",
                        "descritpion": "启用",
                        "permissionId": 14,
                        "perName": "启用",
                        "url": "",
                        "type": "3",
                        "pid": 2,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 14:24:32",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 14:24:30",
                "descritpion": "首页功能配置",
                "permissionId": 6,
                "perName": "首页功能配置",
                "url": "",
                "type": "2",
                "pid": 1,
                "icon": "",
                "index": "/featureMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:04:39",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:04:37",
                        "descritpion": "新增",
                        "permissionId": 15,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 6,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:05:17",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:05:15",
                        "descritpion": "编辑",
                        "permissionId": 16,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 6,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:06:00",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:05:57",
                        "descritpion": "删除",
                        "permissionId": 17,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 6,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:09:40",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:09:38",
                        "descritpion": "启用",
                        "permissionId": 18,
                        "perName": "启用",
                        "url": "",
                        "type": "3",
                        "pid": 6,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:10:12",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:10:09",
                        "descritpion": "禁用",
                        "permissionId": 19,
                        "perName": "禁用",
                        "url": "",
                        "type": "3",
                        "pid": 6,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 14:25:29",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 14:25:27",
        "descritpion": "资讯管理",
        "permissionId": 7,
        "perName": "资讯管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-news",
        "index": "2",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 14:26:08",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 14:26:06",
                "descritpion": "资讯分类管理",
                "permissionId": 8,
                "perName": "资讯分类管理",
                "url": "",
                "type": "2",
                "pid": 7,
                "icon": "",
                "index": "/newsMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:27:06",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:27:04",
                        "descritpion": "新增",
                        "permissionId": 9,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 8,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:28:16",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:28:14",
                        "descritpion": "编辑",
                        "permissionId": 10,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 8,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 14:28:41",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 14:28:39",
                        "descritpion": "删除",
                        "permissionId": 11,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 8,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:11:24",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:11:21",
                        "descritpion": "启用",
                        "permissionId": 20,
                        "perName": "启用",
                        "url": "",
                        "type": "3",
                        "pid": 8,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:11:52",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:11:49",
                        "descritpion": "禁用",
                        "permissionId": 21,
                        "perName": "禁用",
                        "url": "",
                        "type": "3",
                        "pid": 8,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 14:29:52",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 14:29:48",
                "descritpion": "资讯发布管理",
                "permissionId": 12,
                "perName": "资讯发布管理",
                "url": "",
                "type": "2",
                "pid": 7,
                "icon": "",
                "index": "/newsPublishMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:13:06",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:13:03",
                        "descritpion": "新增",
                        "permissionId": 22,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 12,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:13:52",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:13:50",
                        "descritpion": "编辑",
                        "permissionId": 23,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 12,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:14:21",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:14:19",
                        "descritpion": "删除",
                        "permissionId": 24,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 12,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 15:14:57",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 15:14:55",
                        "descritpion": "审核",
                        "permissionId": 25,
                        "perName": "审核",
                        "url": "",
                        "type": "3",
                        "pid": 12,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 15:15:35",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 15:15:32",
        "descritpion": "机构管理",
        "permissionId": 26,
        "perName": "机构管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-location-outline",
        "index": "3",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 15:16:36",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 15:16:34",
                "descritpion": "机构列表",
                "permissionId": 27,
                "perName": "机构列表",
                "url": "",
                "type": "2",
                "pid": 26,
                "icon": "",
                "index": "/orgMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:59:38",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:59:36",
                        "descritpion": "新增",
                        "permissionId": 106,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 27,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 18:00:04",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 18:00:02",
                        "descritpion": "编辑",
                        "permissionId": 107,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 27,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 18:00:32",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 18:00:30",
                        "descritpion": "删除",
                        "permissionId": 108,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 27,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 18:00:55",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 18:00:52",
                        "descritpion": "刷新",
                        "permissionId": 109,
                        "perName": "刷新",
                        "url": "",
                        "type": "3",
                        "pid": 27,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 18:01:14",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 18:01:11",
                        "descritpion": "审核",
                        "permissionId": 110,
                        "perName": "审核",
                        "url": "",
                        "type": "3",
                        "pid": 27,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 15:17:18",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 15:17:15",
        "descritpion": "视频管理",
        "permissionId": 28,
        "perName": "视频管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-view",
        "index": "4",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 15:18:47",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 15:18:44",
                "descritpion": "视频列表",
                "permissionId": 29,
                "perName": "视频列表",
                "url": "",
                "type": "2",
                "pid": 28,
                "icon": "",
                "index": "/videoMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:12:42",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:12:38",
                        "descritpion": "新增",
                        "permissionId": 30,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 29,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:13:05",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:13:02",
                        "descritpion": "编辑",
                        "permissionId": 31,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 29,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:13:28",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:13:26",
                        "descritpion": "删除",
                        "permissionId": 32,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 29,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:13:50",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:13:48",
                        "descritpion": "审核",
                        "permissionId": 33,
                        "perName": "审核",
                        "url": "",
                        "type": "3",
                        "pid": 29,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 16:14:37",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 16:14:34",
                "descritpion": "视频类型",
                "permissionId": 34,
                "perName": "视频类型",
                "url": "",
                "type": "2",
                "pid": 28,
                "icon": "",
                "index": "/videoTypeMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:15:22",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:15:18",
                        "descritpion": "新增",
                        "permissionId": 35,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 34,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:15:47",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:15:44",
                        "descritpion": "编辑",
                        "permissionId": 36,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 34,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:16:11",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:16:07",
                        "descritpion": "删除",
                        "permissionId": 37,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 34,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:16:34",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:16:32",
                        "descritpion": "刷新",
                        "permissionId": 38,
                        "perName": "刷新",
                        "url": "",
                        "type": "3",
                        "pid": 34,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 16:38:03",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 16:38:06",
        "descritpion": "指南管理",
        "permissionId": 39,
        "perName": "指南管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-document",
        "index": "5",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 16:38:42",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 16:38:40",
                "descritpion": "指南列表",
                "permissionId": 40,
                "perName": "指南列表",
                "url": "",
                "type": "2",
                "pid": 39,
                "icon": "",
                "index": "/guideMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:39:22",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:39:20",
                        "descritpion": "新增",
                        "permissionId": 41,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 40,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:39:42",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:39:40",
                        "descritpion": "编辑",
                        "permissionId": 42,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 40,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:40:05",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:40:03",
                        "descritpion": "删除",
                        "permissionId": 43,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 40,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:40:31",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:40:29",
                        "descritpion": "审核",
                        "permissionId": 44,
                        "perName": "审核",
                        "url": "",
                        "type": "3",
                        "pid": 40,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 16:40:56",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 16:40:54",
        "descritpion": "活动管理",
        "permissionId": 45,
        "perName": "活动管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-star-off",
        "index": "6",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 16:41:43",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 16:41:41",
                "descritpion": "活动列表",
                "permissionId": 46,
                "perName": "活动列表",
                "url": "",
                "type": "2",
                "pid": 45,
                "icon": "",
                "index": "/activityMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:42:27",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:42:25",
                        "descritpion": "新增",
                        "permissionId": 47,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 46,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:42:47",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:42:45",
                        "descritpion": "删除",
                        "permissionId": 48,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 46,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 16:43:18",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 16:43:16",
                "descritpion": "待审核活动",
                "permissionId": 49,
                "perName": "待审核活动",
                "url": "",
                "type": "2",
                "pid": 45,
                "icon": "",
                "index": "/activityAuditMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 16:43:56",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 16:43:54",
                        "descritpion": "审核",
                        "permissionId": 50,
                        "perName": "审核",
                        "url": "",
                        "type": "3",
                        "pid": 49,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 16:44:31",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 16:44:28",
        "descritpion": "就业管理",
        "permissionId": 51,
        "perName": "就业管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-edit-outline",
        "index": "7",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:07:13",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:07:11",
                "descritpion": "人力资源管理（信息）",
                "permissionId": 52,
                "perName": "人力资源管理（信息）",
                "url": "",
                "type": "2",
                "pid": 51,
                "icon": "",
                "index": "/jobMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:07:39",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:07:37",
                "descritpion": "人力资讯管理（通告）",
                "permissionId": 53,
                "perName": "人力资讯管理（通告）",
                "url": "",
                "type": "2",
                "pid": 51,
                "icon": "",
                "index": "/hireMg",
                "roles": [],
                "child": []
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 17:08:47",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 17:08:44",
        "descritpion": "社区管理",
        "permissionId": 54,
        "perName": "社区管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-rank",
        "index": "8",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:09:21",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:09:19",
                "descritpion": "社区列表",
                "permissionId": 55,
                "perName": "社区列表",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/communityMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:09:52",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:09:50",
                "descritpion": "社区架构",
                "permissionId": 56,
                "perName": "社区架构",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/structureMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:10:16",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:10:14",
                "descritpion": "居民投票",
                "permissionId": 57,
                "perName": "居民投票",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/voteMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:10:40",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:10:38",
                "descritpion": "社区风采",
                "permissionId": 58,
                "perName": "社区风采",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/pictureWallMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:11:02",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:11:00",
                "descritpion": "预约场地",
                "permissionId": 59,
                "perName": "预约场地",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/siteMg",
                "roles": [],
                "child": []
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:11:29",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:11:27",
                "descritpion": "预约社工",
                "permissionId": 60,
                "perName": "预约社工",
                "url": "",
                "type": "2",
                "pid": 54,
                "icon": "",
                "index": "/workerMg",
                "roles": [],
                "child": []
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 17:11:51",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 17:11:48",
        "descritpion": "内容管理",
        "permissionId": 61,
        "perName": "内容管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-service",
        "index": "9",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:13:44",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:13:41",
                "descritpion": "首页皮肤管理",
                "permissionId": 62,
                "perName": "首页皮肤管理",
                "url": "",
                "type": "2",
                "pid": 61,
                "icon": "",
                "index": "/skinMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:14:51",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:14:48",
                        "descritpion": "新增",
                        "permissionId": 63,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 62,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:15:12",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:15:08",
                        "descritpion": "编辑",
                        "permissionId": 64,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 62,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:15:38",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:15:35",
                        "descritpion": "删除",
                        "permissionId": 65,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 62,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:16:02",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:16:00",
                        "descritpion": "禁用",
                        "permissionId": 66,
                        "perName": "禁用",
                        "url": "",
                        "type": "3",
                        "pid": 62,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:16:22",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:16:20",
                        "descritpion": "启用",
                        "permissionId": 67,
                        "perName": "启用",
                        "url": "",
                        "type": "3",
                        "pid": 62,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:16:49",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:16:47",
                "descritpion": "常见问题答疑",
                "permissionId": 68,
                "perName": "常见问题答疑",
                "url": "",
                "type": "2",
                "pid": 61,
                "icon": "",
                "index": "/questionMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:17:38",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:17:27",
                        "descritpion": "新增",
                        "permissionId": 69,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 68,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:18:32",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:18:30",
                        "descritpion": "编辑",
                        "permissionId": 70,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 68,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:18:51",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:18:49",
                        "descritpion": "删除",
                        "permissionId": 71,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 68,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:19:22",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:19:19",
                "descritpion": "意见反馈管理",
                "permissionId": 72,
                "perName": "意见反馈管理",
                "url": "",
                "type": "2",
                "pid": 61,
                "icon": "",
                "index": "/feedbackMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:20:31",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:20:28",
                        "descritpion": "回复",
                        "permissionId": 73,
                        "perName": "回复",
                        "url": "",
                        "type": "3",
                        "pid": 72,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:21:00",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:20:58",
                        "descritpion": "编辑自动回复内容",
                        "permissionId": 74,
                        "perName": "编辑自动回复内容",
                        "url": "",
                        "type": "3",
                        "pid": 72,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:21:20",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:21:18",
                        "descritpion": "删除",
                        "permissionId": 75,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 72,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:21:45",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:21:43",
                        "descritpion": "刷新",
                        "permissionId": 76,
                        "perName": "刷新",
                        "url": "",
                        "type": "3",
                        "pid": 72,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 17:22:24",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 17:22:21",
        "descritpion": "用户管理",
        "permissionId": 77,
        "perName": "用户管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-edit-outline",
        "index": "10",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:24:34",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:24:32",
                "descritpion": "管理端用户",
                "permissionId": 78,
                "perName": "管理端用户",
                "url": "",
                "type": "2",
                "pid": 77,
                "icon": "",
                "index": "/userMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:25:30",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:25:28",
                        "descritpion": "新增",
                        "permissionId": 79,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 78,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:25:52",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:25:50",
                        "descritpion": "编辑",
                        "permissionId": 80,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 78,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:26:23",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:26:21",
                        "descritpion": "重置密码",
                        "permissionId": 81,
                        "perName": "重置密码",
                        "url": "",
                        "type": "3",
                        "pid": 78,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:26:44",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:26:41",
                        "descritpion": "删除",
                        "permissionId": 82,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 78,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:28:32",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:28:30",
                "descritpion": "APP端用户",
                "permissionId": 83,
                "perName": "APP端用户",
                "url": "",
                "type": "2",
                "pid": 77,
                "icon": "",
                "index": "/appUserMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:29:35",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:29:32",
                        "descritpion": "重置密码",
                        "permissionId": 84,
                        "perName": "重置密码",
                        "url": "",
                        "type": "3",
                        "pid": 83,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:29:56",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:29:53",
                        "descritpion": "删除",
                        "permissionId": 85,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 83,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    },
    {
        "id": null,
        "creatorID": null,
        "creatorName": "1",
        "createTime": "2018-09-17 17:30:50",
        "status": 1,
        "statusDesc": null,
        "updateUser": 1,
        "updateTime": "2018-09-17 17:30:48",
        "descritpion": "系统管理",
        "permissionId": 86,
        "perName": "系统管理",
        "url": "",
        "type": "1",
        "pid": -1,
        "icon": "el-icon-setting",
        "index": "11",
        "roles": [],
        "child": [
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:32:49",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:32:47",
                "descritpion": "部门管理",
                "permissionId": 87,
                "perName": "部门管理",
                "url": "",
                "type": "2",
                "pid": 86,
                "icon": "",
                "index": "/depMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:34:23",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:34:21",
                        "descritpion": "新增",
                        "permissionId": 88,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 87,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:34:47",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:34:44",
                        "descritpion": "编辑",
                        "permissionId": 89,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 87,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:35:07",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:35:05",
                        "descritpion": "删除",
                        "permissionId": 90,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 87,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:35:31",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:35:29",
                        "descritpion": "刷新",
                        "permissionId": 91,
                        "perName": "刷新",
                        "url": "",
                        "type": "3",
                        "pid": 87,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:35:55",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:35:52",
                "descritpion": "角色管理",
                "permissionId": 92,
                "perName": "角色管理",
                "url": "",
                "type": "2",
                "pid": 86,
                "icon": "",
                "index": "/roleMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:36:42",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:36:39",
                        "descritpion": "新增",
                        "permissionId": 93,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 92,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:37:02",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:37:00",
                        "descritpion": "编辑",
                        "permissionId": 94,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 92,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:37:26",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:37:23",
                        "descritpion": "删除",
                        "permissionId": 95,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 92,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:37:49",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:37:46",
                        "descritpion": "更新权限",
                        "permissionId": 96,
                        "perName": "更新权限",
                        "url": "",
                        "type": "3",
                        "pid": 92,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:38:12",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:38:10",
                "descritpion": "数据字典",
                "permissionId": 97,
                "perName": "数据字典",
                "url": "",
                "type": "2",
                "pid": 86,
                "icon": "",
                "index": "/dicMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:39:09",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:39:07",
                        "descritpion": "新增",
                        "permissionId": 98,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 97,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:39:26",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:39:24",
                        "descritpion": "编辑",
                        "permissionId": 99,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 97,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:39:51",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:39:48",
                        "descritpion": "删除",
                        "permissionId": 100,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 97,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:40:15",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:40:13",
                        "descritpion": "刷新",
                        "permissionId": 101,
                        "perName": "刷新",
                        "url": "",
                        "type": "3",
                        "pid": 97,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            },
            {
                "id": null,
                "creatorID": null,
                "creatorName": "1",
                "createTime": "2018-09-17 17:40:39",
                "status": 1,
                "statusDesc": null,
                "updateUser": 1,
                "updateTime": "2018-09-17 17:40:37",
                "descritpion": "服务项目管理",
                "permissionId": 102,
                "perName": "服务项目管理",
                "url": "",
                "type": "2",
                "pid": 86,
                "icon": "",
                "index": "/serviceMg",
                "roles": [],
                "child": [
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:41:16",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:41:13",
                        "descritpion": "新增",
                        "permissionId": 103,
                        "perName": "新增",
                        "url": "",
                        "type": "3",
                        "pid": 102,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:41:35",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:41:33",
                        "descritpion": "编辑",
                        "permissionId": 104,
                        "perName": "编辑",
                        "url": "",
                        "type": "3",
                        "pid": 102,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    },
                    {
                        "id": null,
                        "creatorID": null,
                        "creatorName": "1",
                        "createTime": "2018-09-17 17:41:53",
                        "status": 1,
                        "statusDesc": null,
                        "updateUser": 1,
                        "updateTime": "2018-09-17 17:41:51",
                        "descritpion": "删除",
                        "permissionId": 105,
                        "perName": "删除",
                        "url": "",
                        "type": "3",
                        "pid": 102,
                        "icon": "",
                        "index": "0",
                        "roles": [],
                        "child": []
                    }
                ]
            }
        ]
    }
]
var x = {}
function b(a) {
    let key = a.index.slice(1)
    x[key] = []
    a.child.forEach(c => {
        x[key].push(c.perName)
    })
}
p.forEach(e1 => {
    e1.child.forEach(e2 => {
        b(e2)
    })
})
console.log(x);




